### ISSUE TITLE
Donation.

### ISSUE THREAD

**Issue by ghost** [jhass/DeBot#3]
@jhass $1 @changetip

**Comment by nahtnam** [comment]
Oops. Misspelled. 

@jhass $1 @changetip

**Comment by changetip** [comment]
Hi @jhass, @nahtnam sent you a Bitcoin tip worth 3,766 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/652132)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by nahtnam** [comment]
@jhass Im tooo adddicccteeeddd!!! $1 @changetip

**Comment by changetip** [comment]
Hi @jhass, I've delivered a Bitcoin tip worth 3,784 bits ($1.00) from @nahtnam to your ChangeTip wallet.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**
