### ISSUE TITLE
Is the project maintained?

### ISSUE THREAD

**Issue by vladfaust** [jhass/DeBot#31]
Hello,

I've checked your project and it's failing to build (or the specs failed) with the latest Crystal (0.26.1) or there are no any specs so the project cannot be validated to be up to date. Your project is in [Awesome Crystal](https://github.com/veelenga/awesome-crystal) list, so I'd like to ask if the project maintained?

I'll initiate a PR to remove your project from the list if you don't respond positively within 7 days.

I'm sorry if I'm wrong, because I've been checking many shards with automated script.

Thanks,
Vlad.

**Comment by jhass** [comment]
It's not actively maintained, it's passively maintained. That is I update it if I have a need to use/rebuild it and I react to pull requests.

**Comment by vladfaust** [comment]
Alright, sorry for disturbing! Note that you can set up daily/weekly tests on Travis so you'll receive a notification when the build starts to fail: https://docs.travis-ci.com/user/cron-jobs.

Thanks.
