### ISSUE TITLE
Matrix support

### ISSUE THREAD

**Issue by peterhoeg** [jhass/DeBot#32]
Are you considering adding support for other networks such as matrix.org?

**Comment by jhass** [comment]
Sorry, no.

**Comment by peterhoeg** [comment]
Would you be open to a PR that adds support for matrix? I would prefer not to start from scratch and not to duplicate efforts if possible.

**Comment by jhass** [comment]
Sorry, that's a no too. I don't use matrix personally so I have no interest in it and won't maintain it or even notice it breaks. Also protocol wise I would be surprised to find any significant overlap, so it really only would be plugin code, which is not that complex.
